.cpp.o:
	g++ -c $(CFLAGS) -o $@ $<

.c.o:
	gcc -c $(CFLAGS) -o $@ $<

bumot: bumot.o bumotdb.o data_connection.o sqlite3.o
	g++ -o $@ $^ $(LIBS)

.PHONY: all clean
all: bumot
clean:
	$(RM) *.o bumot